# Generated by Django 3.0.4 on 2020-07-22 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dlapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='static/media'),
            preserve_default=False,
        ),
    ]
