# Generated by Django 3.0.4 on 2020-07-23 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlapp', '0003_holdings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holdings',
            old_name='a_type',
            new_name='category',
        ),
    ]
