# Generated by Django 3.0.4 on 2021-09-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlapp', '0004_auto_20200723_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='a_type',
            field=models.CharField(choices=[('Journal', 'Journal'), ('Conference', 'Conference'), ('Book', 'Book'), ('Other', 'Other')], default='journal', max_length=10),
        ),
    ]
