# Generated by Django 3.0.4 on 2020-07-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author1', models.CharField(max_length=100)),
                ('author2', models.CharField(max_length=1000)),
                ('a_title', models.CharField(max_length=250)),
                ('a_type', models.CharField(choices=[('journal', 'Journal'), ('conference', 'Conference'), ('book', 'Book'), ('other', 'Other')], default='journal', max_length=10)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.CharField(max_length=100)),
            ],
        ),
    ]
