# Generated by Django 3.0.4 on 2020-07-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlapp', '0002_book_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holdings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('holding', models.FileField(upload_to='static/media')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('authors', models.CharField(max_length=100)),
                ('a_type', models.CharField(choices=[('journal', 'Journal'), ('conference', 'Conference'), ('book', 'Book'), ('other', 'Other')], default='journal', max_length=10)),
                ('uploader', models.CharField(max_length=100)),
            ],
        ),
    ]
